package vista;

import controlador.Ctrl_Representante;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import modelo.Representante;

/**
 *
 * @author andres
 */
public class Inter_representante extends javax.swing.JInternalFrame {

    public Inter_representante() {
        initComponents();
        this.setSize(new Dimension(400, 470));
        this.setTitle("Representantes");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        cedularep = new javax.swing.JTextField();
        nombre2 = new javax.swing.JTextField();
        txtnombre1 = new javax.swing.JTextField();
        apellido1 = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel_wallerpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(402, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Representates.png"))); // NOI18N
        jLabel1.setText("Datos de Representante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Primer Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Segundo Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Primer Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Segundo Apellido:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cedula de Indentidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 210, -1));

        cedularep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedularepActionPerformed(evt);
            }
        });
        getContentPane().add(cedularep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 210, -1));
        getContentPane().add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 210, -1));
        getContentPane().add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, -1));
        getContentPane().add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, -1));
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 210, -1));

        direccion.setColumns(20);
        direccion.setRows(5);
        jScrollPane1.setViewportView(direccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 210, -1));

        jButton1.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jButton1.setText("Ingresar Representante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jButton2.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel_wallerpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel_wallerpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedularepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedularepActionPerformed
        
    }//GEN-LAST:event_cedularepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Representante representante = new Representante();
        Ctrl_Representante controlRep = new Ctrl_Representante();

        //validamos basio
        if (txtnombre1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "tiene que ingresar un nombre y cedula");

        } else {

            if (!controlRep.exiteRep(cedularep.getText().trim())) {
                representante.setPrimernombre(txtnombre1.getText().trim());
                representante.setSegundonombre(nombre2.getText().trim());
                representante.setPrimerapellido(apellido1.getText().trim());
                representante.setSegundoapellido(apellido2.getText().trim());
                representante.setCedula(cedularep.getText().trim());
                representante.setTelefono(telefono.getText().trim());
                representante.setDireccion(direccion.getText().trim());

                if (controlRep.ingresar(representante)) {
                    JOptionPane.showMessageDialog(null, "registro exitoso");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Representante ya registrado");
            }

        }
        //limpiar campo
        txtnombre1.setText("");
        nombre2.setText("");
        apellido1.setText("");
        apellido2.setText("");
        cedularep.setText("");
        telefono.setText("");
        direccion.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //limpiar campo
        txtnombre1.setText("");
        nombre2.setText("");
        apellido1.setText("");
        apellido2.setText("");
        cedularep.setText("");
        telefono.setText("");
        direccion.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JTextField cedularep;
    private javax.swing.JTextArea direccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallerpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField txtnombre1;
    // End of variables declaration//GEN-END:variables
}
